### ISSUE TITLE
请问源码为啥没有上传视频的部分？

### ISSUE THREAD

**Issue by wang836564944** [mindskip/xzs-mysql#367]
demo中是有观看视频的功能的，但是源码中并没有体现。请问可以看看这部分代码吗？

**Comment by mindskip** [comment]
demo是高级版，这是商业版的功能

**Comment by wang836564944** [comment]
请问能不能看一下源码或者技术文档呀？想学习一下，不做商业用途。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "mindskip/xzs-mysql"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月1日(星期二) 中午12:08
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [mindskip/xzs-mysql] 请问源码为啥没有上传视频的部分？ (Issue #367)





 
demo是高级版，这是商业版的功能
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
